# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e1c950bbe3698cdad4f4bc8c40ea1a623d8dcc96cee10c62b67239220a2ce4c801c0234f1d12db3eeb47d1673a706ec185c2b972641012cb0484c9332f5a21

test:
  secret_key_base: 14a2732b591df53303b7e37ee140307b22596d4087fc726f81d58ac391d22e05d92984443970cfc88cca751968767fca7336a20e25c9f73dc097f51491e72b8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
